version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3050:3050"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped